<?xml version="1.0" encoding="utf-8"?><Database Name="Inventory" Class="StockDataDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=(LocalDB)\v11.0;AttachDbFilename=|DataDirectory|\Inventory.mdf;Integrated Security=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="InventoryConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Stock" Member="Stocks">
    <Type Name="Stock">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NChar(100)" CanBeNull="true" />
      <Column Name="Type" Type="System.String" DbType="NChar(100)" CanBeNull="true" />
      <Column Name="Brand" Type="System.String" DbType="NChar(100)" CanBeNull="true" />
      <Column Name="Price" Type="System.String" DbType="NChar(100)" CanBeNull="true" />
    </Type>
  </Table>
</Database>